version: '3.4'

volumes:
  l2_data:

services:
  celestia-das-server:
    platform: linux/amd64
    image: ghcr.io/celestiaorg/nitro-das-celestia:v0.4.0
    ports:
      - "9876:9876"
    entrypoint:
      - "bin/celestia-server"
      - --log-level=5
      - --metrics
      - --enable-rpc=true
      - --rpc-addr=0.0.0.0
      - --rpc-port=9876
      - --celestia.keyname=${CELESTIA_KEYNAME}
      - --celestia.auth-token=${CELESTIA_LIGHT_NODE_AUTH_TOKEN}
      - --celestia.namespace-id=ca1de12a12528b03789c
      - --celestia.rpc=${CELESTIA_LIGHT_NODE}
      - --celestia.validator-config.blobstream=0xA83ca7775Bc2889825BcDeDfFa5b758cf69e8794
      - --celestia.validator-config.eth-rpc=https://arb-mainnet.g.alchemy.com/v2/${API_KEY_ALCHEMY}

  l2:
    platform: linux/amd64
    image: ghcr.io/celestiaorg/nitro:v3.5.2
    ports:
      - "8545:8545"
      - "8546:8546"
    volumes:
      - "${PWD}/nodeConfig.json:/config/nodeConfig.json"
      - "${PWD}/l2_data:/home/user/.arbitrum"
    entrypoint:
      - "/usr/local/bin/nitro"
      - --conf.file=/config/nodeConfig.json
      - --execution.forwarding-target=wss://tranched-mainnet.calderachain.xyz/ws
      - --node.feed.input.url=wss://tranched-mainnet.calderachain.xyz/feed
      - --node.data-availability.rest-aggregator.urls="https://tranched-mainnet.calderachain.xyz/rest-aggregator"
      - --parent-chain.connection.url=https://base-mainnet.g.alchemy.com/v2/${API_KEY_ALCHEMY}